
    # stages:
    #  - build-and-test
    #  - deploy

    #test:latest:
    #  stage: build-and-test
    #  image: gitlab-research.centralesupelec.fr:4567/2017bentrioum/markovprocesses.jl/julia:latest
    #  script:
    #    - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=".")); Pkg.instantiate(); Pkg.test("MarkovProcesses")'
    #  tags:
    #    - docker

pages:
  stage: deploy
  image: gitlab-research.centralesupelec.fr:4567/2017bentrioum/markovprocesses.jl/julia:latest
  script:
    - apt-get update -qq && apt-get install -y git
    - echo $CI_COMMIT_BRANCH
    - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=".")); Pkg.instantiate();'
    - julia --project=docs/ --color=yes docs/make.jl  # make documentation
    - mkdir public
    - mkdir public/dev
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - docker
#   only:
#     - ci_tests
#
