build-doc:
    image: julia:latest
    stage: build
    script:
        - "julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd(), subdir=\"core/\")); Pkg.instantiate()'"
        - "julia --project=docs/ docs/make.jl"
