build-doc:
    stage: build
    image: julia:1.6
    script:
        - "julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'"
        - "julia --project=docs/ docs/make.jl"

